/*
 * Whether a C2PA asset declares that it was generated by AI.
 *
 * The only honest source for this is the IPTC `digitalSourceType` recorded in
 * the asset's `c2pa.actions` assertion. It is a statement the producer signed
 * about the CONTENT.
 *
 * What this deliberately does NOT do is infer AI from who signed the file.
 * The extension used to report `isAIDetected` when the signer matched a trust
 * list named "AI trust list", whose entities are Microsoft (as a CA) and
 * OpenAI. Because a CA match covers every leaf certificate beneath it, an
 * ordinary photograph signed anywhere under Microsoft's PKI was labelled
 * AI-generated, while genuine AI output signed by any other vendor was not.
 * Signer identity and content origin are different questions.
 *
 * Only trained-model output counts. `algorithmicMedia` covers procedural and
 * algorithmic work (a rendered gradient, a computed chart) that no reasonable
 * reader would call AI-generated, so it is excluded.
 */

const IPTC_PREFIX = 'http://cv.iptc.org/newscodes/digitalsourcetype/'

/** Fully machine-generated by a trained model. */
export const TRAINED_ALGORITHMIC_MEDIA = `${IPTC_PREFIX}trainedAlgorithmicMedia`
/** Human-authored work containing trained-model elements. */
export const COMPOSITE_WITH_TRAINED_ALGORITHMIC_MEDIA = `${IPTC_PREFIX}compositeWithTrainedAlgorithmicMedia`

export type AiGeneration =
  /** No AI declared, or nothing said at all. */
  | 'none'
  /** Contains AI-generated elements alongside human-authored content. */
  | 'partial'
  /** Wholly generated by a trained model. */
  | 'full'

export interface AiDetectionResult {
  generation: AiGeneration
  /** The declared digitalSourceType URI, verbatim, or null when absent. */
  digitalSourceType: string | null
}

const NONE: AiDetectionResult = { generation: 'none', digitalSourceType: null }

/**
 * Compare a declared source type against the trained-model codes.
 *
 * Matches on the trailing code rather than the whole URI: the IPTC vocabulary
 * is published under both http and https, and some producers emit the bare
 * code. Case-insensitive because the codes are camelCase by convention, not by
 * enforcement.
 */
function classify (raw: unknown): AiGeneration {
  if (typeof raw !== 'string' || raw === '') return 'none'
  const code = raw.split('/').pop()?.toLowerCase() ?? ''
  if (code === 'trainedalgorithmicmedia') return 'full'
  if (code === 'compositewithtrainedalgorithmicmedia') return 'partial'
  return 'none'
}

/**
 * Walk an assertion payload for `digitalSourceType`, wherever it sits.
 *
 * The key appears per-action in `c2pa.actions`/`c2pa.actions.v2`, and some
 * producers also place it at the assertion root. The structure is
 * attacker-supplied, so this only reads and never throws: an unreadable
 * payload yields "nothing declared", never a false AI verdict.
 */
function collect (value: unknown, found: string[], depth = 0): void {
  if (depth > 6 || value == null || typeof value !== 'object') return
  if (Array.isArray(value)) {
    for (const item of value) collect(item, found, depth + 1)
    return
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    if (key === 'digitalSourceType' && typeof child === 'string') found.push(child)
    else collect(child, found, depth + 1)
  }
}

/**
 * Read the AI-generation claim from a manifest's actions assertions.
 *
 * @param activeManifest the ACTIVE manifest from the c2pa-rs store. Only its
 *   own assertions are considered: an ingredient being AI-generated does not
 *   make the asset that consumed it AI-generated, and saying otherwise would
 *   label a human edit of an AI image identically to the image itself.
 */
export function detectAiGeneration (activeManifest: unknown): AiDetectionResult {
  const assertions = (activeManifest as { assertions?: unknown })?.assertions
  if (!Array.isArray(assertions)) return NONE

  const declared: string[] = []
  for (const assertion of assertions) {
    const label = (assertion as { label?: unknown })?.label
    if (typeof label !== 'string' || !label.startsWith('c2pa.actions')) continue
    collect((assertion as { data?: unknown })?.data, declared)
  }
  if (declared.length === 0) return NONE

  // A composite may carry several actions; the strongest claim wins, so an
  // asset declaring any wholly-generated action is reported as such.
  let best: AiGeneration = 'none'
  let bestType: string | null = null
  for (const raw of declared) {
    const verdict = classify(raw)
    if (verdict === 'full') return { generation: 'full', digitalSourceType: raw }
    if (verdict === 'partial' && best === 'none') { best = 'partial'; bestType = raw }
  }
  return best === 'none' ? NONE : { generation: best, digitalSourceType: bestType }
}
