name: Build Browser Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out repository code

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Upload Chrome dist folder's zip as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-chrome
        path: dist/chrome/

    - name: Upload Firefox dist folder's zip as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-firefox
        path: dist/firefox/
